### ISSUE TITLE
Can't send e-mails in Version 3.x

### ISSUE THREAD

**Issue by clipper72** [Xenon-s/ioBroker.device-reminder#363] opened 2023-12-09 20:56 UTC
**Describe the bug**  
In the actual version 3.x I can't send mails anymore. Alexa works fine, but Mails not.

In version 2.x, only mails for the start were sent. Now nothing is sent any more. I have already completely reinstalled and reconfigured the adapter, but that didn't help. The mail adapter sends the test mail and other mails without any problems.

**Versions:**  
 - Adapter version: 3.0.0
 - JS-Controller version: 5.0.16 
 - Node version: v18.17.1
 - Operating system: Raspi

**Comment by Xenon-s** [comment] 2023-12-22 07:26
Has anything changed in the email adapter? I have not changed anything from the previous version

**Comment by Xenon-s** [comment] 2023-12-22 07:41
This is the syntax in Blockly:

![image](https://github.com/Xenon-s/ioBroker.device-reminder/assets/65488191/41cf8419-2d31-4c88-8d2d-11d4d633f36c)

and the adapter works in exactly the same way:

![image](https://github.com/Xenon-s/ioBroker.device-reminder/assets/65488191/468ffb86-116b-424b-92b7-306acc7bfaa4)

**Comment by gigabyte76** [comment] 2024-01-10 19:30
hi, i have the same issues. 
under version 2.x it works great. but now under 3 i get no emails.

Node.js: v18.17.1(18.19.0)
NPM: 9.6.7(10.2.3)

email provider -> v1.2.1

if i send a test mail via the mail provider, i get the test mail without problems.

**Comment by kuckuckmann** [comment] 2024-01-13 22:17
I can confirm, it's not working in v3.0.1

**Comment by Xenon-s** [comment] 2024-01-15 14:31
Bug found, will be fixed with the 3.1.0 - beta here on github. Since this is a github beta, various log messages (info) will appear. These will help me to help you in case of problems. Please do not create a new issue because of these messages!

**Closed by Xenon-s** 2024-01-15 14:31 UTC
Labels: bug, question, In progress

**Comment by clipper72** [comment] 2024-02-03 15:33
Thank you for your work. I installed the GitHub version 3.1.2 In the last days and tested it with our washing machine. Now it works like expected and sends mails.
